@rem make all eligible combinations
gcc -o chip1-bfs.exe bfs.c chip1.c -O3 -Wall
gcc -o chip1-bfs2.exe bfs2.c chip1.c -O3 -Wall
gcc -o chip1-bfs2p.exe bfs2p.c chip1.c -O3 -Wall
gcc -o chip1-bfsd.exe bfsd.c chip1.c -O3 -Wall
gcc -o soko-bfs.exe bfs.c soko.c -O3 -Wall
gcc -o soko-bfs2.exe bfs2.c soko.c -O3 -Wall
gcc -o soko-bfs2p.exe bfs2p.c soko.c -O3 -Wall
gcc -o soko-bfsd.exe bfsd.c soko.c -O3 -Wall
gcc -o soko2-bfs.exe bfs.c soko2.c -O3 -Wall
gcc -o soko2-bfs2.exe bfs2.c soko2.c -O3 -Wall
gcc -o soko2-bfs2p.exe bfs2p.c soko2.c -O3 -Wall
gcc -o soko2-bfsd.exe bfsd.c soko2.c -O3 -Wall
gcc -o soko-lx-bfs.exe bfs.c soko-lx.c -O3 -Wall
gcc -o soko-lx-bfs2.exe bfs2.c soko-lx.c -O3 -Wall
gcc -o soko-lx-bfs2p.exe bfs2p.c soko-lx.c -O3 -Wall
gcc -o soko-lx-bfsd.exe bfsd.c soko-lx.c -O3 -Wall
gcc -o sokobomb-lx-bfs.exe bfs.c sokobomb-lx.c -O3 -Wall
gcc -o sokobomb-lx-bfs2.exe bfs2.c sokobomb-lx.c -O3 -Wall
gcc -o sokobomb-lx-bfs2p.exe bfs2p.c sokobomb-lx.c -O3 -Wall
gcc -o sokobomb-lx-bfsd.exe bfsd.c sokobomb-lx.c -O3 -Wall
gcc -o npuzzle-bfs.exe bfs.c npuzzle.c -O3 -Wall
gcc -o npuzzle-bfs2.exe bfs2.c npuzzle.c -O3 -Wall
gcc -o npuzzle-bfs2p.exe bfs2p.c npuzzle.c -O3 -Wall
gcc -o npuzzle-bfsd.exe bfsd.c npuzzle.c -O3 -Wall
gcc -o npuzzle-bfsdu.exe bfsdu.c npuzzle.c -O3 -Wall
gcc -o plank-bfs.exe bfs.c plank.c -O3 -Wall
gcc -o plank-bfs2.exe bfs2.c plank.c -O3 -Wall
gcc -o plank-bfs2p.exe bfs2p.c plank.c -O3 -Wall
gcc -o plank-bfsd.exe bfsd.c plank.c -O3 -Wall
gcc -o plank-bfsdu.exe bfsdu.c plank.c -O3 -Wall
